apiVersion: apps/v1
kind: Deployment 
metadata:
  name: devops-practices-k8s-deployment
spec:
  selector:
    matchLabels:
      app: devops-practices-k8s
  replicas: 1 
  template:
    metadata:
      labels:
        app: devops-practices-k8s
    spec:
      containers:
        - name: devops-practices-k8s
          image: liberosis8803/devopslab2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: devops-practices-k8s-svc
spec:
  selector:
    app: devops-practices-k8s
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 8080
  type: NodePort
